#!/usr/bin/env python3

"""mpi_python_format

Format python files. This files are either directly given as argument or found
in a folder also given as argument.

License BSD-3-Clause
Copyright (c) 2021, New York University and Max Planck Gesellschaft.
"""

import sys
from mpi_cmake_modules.python_format import run_python_format

if __name__ == "__main__":
    try:
        run_python_format(sys.argv)
    except Exception as e:
        import traceback

        traceback.print_exc()
        print("\nfailed with error:\n" + str(e) + "\n")
