#!/usr/bin/env python

"""mpi_cpp_format

Format C/C++ files. This files are either directly given as argument or found
in a folder also given as argument.

License BSD-3-Clause
Copyright (c) 2019, New York University and Max Planck Gesellschaft.
"""

import sys
from mpi_cmake_modules.cpp_format import run_cpp_format

if __name__ == "__main__":
    try:
        run_cpp_format(sys.argv)
    except Exception as e:
        import traceback

        traceback.print_exc()
        print("\nfailed with error:\n" + str(e) + "\n")
