#!/bin/sh
#
# Build documentation
#
# License BSD-3-Clause
# Copyright (c) 2021, New York University and Max Planck Gesellschaft.

echo "WARNING: mpi_doc_build is deprecated. Use breathing-cat (`bcat`) instead."

bcat "$@"
