#!/usr/bin/env python3

"""mpi_doc_build

Build documentation

License BSD-3-Clause
Copyright (c) 2021, New York University and Max Planck Gesellschaft.
"""

import argparse
from pathlib import Path
from mpi_cmake_modules.documentation_builder import (
    build_documentation,
)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process some integers.")
    parser.add_argument(
        "build_dir",
        type=str,
        help="Directory where to build the documentation",
    )
    parser.add_argument(
        "project_source_dir",
        type=str,
        help="Directory where source files are.",
    )
    parser.add_argument(
        "project_version",
        type=str,
        help="Directory where source files are.",
    )

    args = parser.parse_args()

    build_documentation(
        args.build_dir, args.project_source_dir, args.project_version
    )
